# Generated by Django 2.1.2 on 2018-12-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
    ]
