# Generated by Django 2.1.2 on 2018-12-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
