# Generated by Django 2.1.2 on 2018-12-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
