# Generated by Django 2.1.2 on 2018-12-13 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='avatar_url',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator], verbose_name='Avatar of the github user'),
        ),
    ]
