# Generated by Django 2.1.2 on 2018-12-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('users', '0011_socialaccount_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.SocialAccount')),
            ],
            bases=('socialaccount.socialaccount',),
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='socialaccount_ptr',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
