# Generated by Django 2.1.2 on 2018-12-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('users', '0013_github_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='socialaccount_ptr',
        ),
        migrations.DeleteModel(
            name='Github',
        ),
    ]
