# Generated by Django 2.1.2 on 2018-11-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181112_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='mainBlog.png', upload_to='thumbnails/'),
        ),
    ]
