# Generated by Django 2.1.2 on 2018-12-03 15:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181203_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(default='mainBlog.png', upload_to='thumbnails/'),
        ),
    ]
